language: cpp
matrix:
  include:
    - os: osx
      env:
        - CMAKE_PREFIX_PATH=/usr/local/opt/qt
    - os: linux
      sudo: required
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install clang-tools-extra || true; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install clang-tidy || true; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install clang-format || true; fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -f test/build/Dockerfile .; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir build ; cd build; cmake .. ; make -j2; make -j2 lint; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cpack -D CPACK_PACKAGE_FILE_NAME=veles-osx -G "DragNDrop;ZIP"; fi
