language: cpp
matrix:
  include:
    - compiler: clang
      os: osx
    - compiler: clang
      os: linux
    - compiler: gcc
      os: linux
script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j2
  - make lint
