language: cpp
matrix:
  include:
    - os: osx
      env:
        - CMAKE_PREFIX_PATH=/usr/local/opt/qt
    - os: linux
      sudo: required
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install llvm --with-clang --with-clang-extra-tools; fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -f test/build/Dockerfile .; fi
  - env
  - mkdir build
  - cd build
  - cmake ..
  - make -j2
  - make lint
